from __future__ import annotations

import json
from typing import Any

from app.agents.common.runtime_context import AgentDependencies
from app.agents.common.sql_quality import optimize_sql_with_guardrails


def build_tools(deps: AgentDependencies) -> list:
    """Build tools for SQL generation agent.

    Args:
        deps: Shared runtime dependencies containing settings.

    Returns:
        List of generation helper tools used by the LLM.
    """

    async def normalize_generated_sql(sql: str, tool_context: Any | None = None) -> dict[str, Any]:
        """Normalize generated SQL and apply baseline guardrail rewrites.

        Args:
            sql: Candidate SQL text generated by the LLM.
            tool_context: ADK context used to persist normalized SQL.

        Returns:
            Payload with normalized SQL and automatic rewrite details.
        """

        optimized = optimize_sql_with_guardrails(deps.settings.default_limit, sql)
        payload = {
            "normalized_sql": optimized["optimized_sql"],
            "changes": optimized["changes"],
            "tables": optimized["tables"],
        }

        if tool_context:
            tool_context.state["generated_sql"] = payload["normalized_sql"]
            tool_context.state["submitted_sql"] = payload["normalized_sql"]
            tool_context.state["generator_normalization_json"] = json.dumps(payload)
        return payload

    async def generation_constraints(tool_context: Any | None = None) -> dict[str, Any]:
        """Return explicit SQL generation constraints for enterprise guardrails.

        Args:
            tool_context: ADK context used to persist constraint payload.

        Returns:
            Constraint dictionary listing read-only and quality requirements.
        """

        payload = {
            "read_only": True,
            "avoid_select_star": True,
            "must_use_explicit_joins": True,
            "default_limit": deps.settings.default_limit,
        }

        if tool_context:
            tool_context.state["generation_constraints_json"] = json.dumps(payload)
        return payload

    return [generation_constraints, normalize_generated_sql]
