from __future__ import annotations

import asyncio
from collections.abc import Mapping
from collections.abc import Sequence
from datetime import datetime
import json
import re
from typing import TYPE_CHECKING
import uuid

from google.adk.memory.base_memory_service import BaseMemoryService
from google.adk.memory.base_memory_service import SearchMemoryResponse
from google.adk.memory.memory_entry import MemoryEntry
from google.genai import types

if TYPE_CHECKING:
    from google.adk.events.event import Event
    from google.adk.sessions.session import Session

_UNKNOWN_SESSION_ID = "__unknown_session_id__"
_WORD_PATTERN = re.compile(r"[A-Za-z0-9_]+")


class PostgresMemoryService(BaseMemoryService):
    """PostgreSQL-backed ADK memory service for persistent long-term memory."""

    def __init__(self, dsn: str, schema: str = "public", max_results: int = 20):
        self._dsn = (dsn or "").strip()
        if not self._dsn:
            raise ValueError("DATA_ASSIST_ADK_POSTGRES_DSN is required for ADK memory persistence")

        self._schema = self._validate_identifier(schema or "public")
        self._max_results = max(1, int(max_results or 20))

        try:
            import psycopg  # type: ignore
        except ImportError as exc:  # pragma: no cover - runtime dependency path
            raise RuntimeError(
                "PostgreSQL memory persistence requires psycopg. Install with `pip install psycopg[binary]`."
            ) from exc

        self._psycopg = psycopg
        schema_ident = self._quote_ident(self._schema)
        self._table_ref = f"{schema_ident}.adk_memory_entries"
        self._init_schema()

    @staticmethod
    def _validate_identifier(value: str) -> str:
        text = (value or "").strip()
        if not text:
            return "public"
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", text):
            raise ValueError(f"Invalid PostgreSQL schema identifier: {value}")
        return text

    @staticmethod
    def _quote_ident(value: str) -> str:
        return f'"{value.replace(chr(34), chr(34) * 2)}"'

    def _connect(self):
        return self._psycopg.connect(self._dsn)

    def _init_schema(self) -> None:
        schema_ident = self._quote_ident(self._schema)
        with self._connect() as conn:
            with conn.cursor() as cur:
                cur.execute(f"CREATE SCHEMA IF NOT EXISTS {schema_ident}")
                cur.execute(
                    f"""
                    CREATE TABLE IF NOT EXISTS {self._table_ref} (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        app_name TEXT NOT NULL,
                        user_id TEXT NOT NULL,
                        session_id TEXT NOT NULL,
                        event_id TEXT NOT NULL,
                        author TEXT,
                        event_timestamp DOUBLE PRECISION,
                        event_timestamp_iso TEXT,
                        content_json JSONB NOT NULL,
                        search_text TEXT NOT NULL,
                        custom_metadata_json JSONB NOT NULL DEFAULT '{{}}'::jsonb,
                        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                        UNIQUE (app_name, user_id, session_id, event_id)
                    )
                    """
                )
                cur.execute(
                    f"""
                    CREATE INDEX IF NOT EXISTS idx_adk_memory_scope_timestamp
                    ON {self._table_ref} (app_name, user_id, event_timestamp DESC)
                    """
                )
                cur.execute(
                    f"""
                    CREATE INDEX IF NOT EXISTS idx_adk_memory_scope_text
                    ON {self._table_ref} (app_name, user_id)
                    """
                )
            conn.commit()

    @staticmethod
    def _extract_text(event: Event) -> str:
        content = getattr(event, "content", None)
        if not content or not content.parts:
            return ""

        chunks: list[str] = []
        for part in content.parts:
            text = getattr(part, "text", None)
            if text:
                stripped = text.strip()
                if stripped:
                    chunks.append(stripped)
        return " ".join(chunks).strip()

    @staticmethod
    def _normalize_metadata(custom_metadata: Mapping[str, object] | None) -> dict[str, object]:
        if not custom_metadata:
            return {}

        normalized: dict[str, object] = {}
        for key, value in custom_metadata.items():
            name = str(key)
            try:
                json.dumps(value)
                normalized[name] = value
            except TypeError:
                normalized[name] = str(value)
        return normalized

    def _build_rows(
        self,
        *,
        app_name: str,
        user_id: str,
        session_id: str,
        events: Sequence[Event],
        custom_metadata: Mapping[str, object] | None = None,
    ) -> list[tuple]:
        metadata = self._normalize_metadata(custom_metadata)
        metadata_json = json.dumps(metadata)

        rows: list[tuple] = []
        for event in events:
            content = getattr(event, "content", None)
            if not content or not content.parts:
                continue

            text = self._extract_text(event)
            if not text:
                continue

            event_id = str(getattr(event, "id", "") or uuid.uuid4())
            author = getattr(event, "author", None)
            timestamp = float(getattr(event, "timestamp", 0.0) or 0.0)
            timestamp_iso = datetime.fromtimestamp(timestamp).isoformat() if timestamp > 0 else None
            payload = json.dumps(content.model_dump(mode="json"))

            rows.append(
                (
                    app_name,
                    user_id,
                    session_id,
                    event_id,
                    author,
                    timestamp,
                    timestamp_iso,
                    payload,
                    text,
                    metadata_json,
                )
            )
        return rows

    def _upsert_rows(self, rows: list[tuple]) -> None:
        if not rows:
            return

        with self._connect() as conn:
            with conn.cursor() as cur:
                cur.executemany(
                    f"""
                    INSERT INTO {self._table_ref} (
                        app_name,
                        user_id,
                        session_id,
                        event_id,
                        author,
                        event_timestamp,
                        event_timestamp_iso,
                        content_json,
                        search_text,
                        custom_metadata_json
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s::jsonb, %s, %s::jsonb)
                    ON CONFLICT (app_name, user_id, session_id, event_id)
                    DO UPDATE SET
                        author = EXCLUDED.author,
                        event_timestamp = EXCLUDED.event_timestamp,
                        event_timestamp_iso = EXCLUDED.event_timestamp_iso,
                        content_json = EXCLUDED.content_json,
                        search_text = EXCLUDED.search_text,
                        custom_metadata_json = EXCLUDED.custom_metadata_json
                    """,
                    rows,
                )
            conn.commit()

    async def add_session_to_memory(self, session: Session) -> None:
        rows = self._build_rows(
            app_name=session.app_name,
            user_id=session.user_id,
            session_id=session.id,
            events=session.events,
        )
        await asyncio.to_thread(self._upsert_rows, rows)

    async def add_events_to_memory(
        self,
        *,
        app_name: str,
        user_id: str,
        events: Sequence[Event],
        session_id: str | None = None,
        custom_metadata: Mapping[str, object] | None = None,
    ) -> None:
        scoped_session_id = session_id or _UNKNOWN_SESSION_ID
        rows = self._build_rows(
            app_name=app_name,
            user_id=user_id,
            session_id=scoped_session_id,
            events=events,
            custom_metadata=custom_metadata,
        )
        await asyncio.to_thread(self._upsert_rows, rows)

    def _search(self, *, app_name: str, user_id: str, query: str) -> list[tuple]:
        words = [word.lower() for word in _WORD_PATTERN.findall(query)]
        if not words:
            return []

        clauses = " OR ".join(["LOWER(search_text) LIKE %s"] * len(words))
        params = [app_name, user_id, *[f"%{word}%" for word in words], self._max_results]

        with self._connect() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    f"""
                    SELECT
                        id,
                        content_json,
                        author,
                        event_timestamp_iso,
                        custom_metadata_json
                    FROM {self._table_ref}
                    WHERE app_name = %s
                      AND user_id = %s
                      AND ({clauses})
                    ORDER BY event_timestamp DESC NULLS LAST, created_at DESC
                    LIMIT %s
                    """,
                    tuple(params),
                )
                return list(cur.fetchall())

    async def search_memory(self, *, app_name: str, user_id: str, query: str) -> SearchMemoryResponse:
        rows = await asyncio.to_thread(self._search, app_name=app_name, user_id=user_id, query=query)
        response = SearchMemoryResponse()
        for row in rows:
            memory_id, content_raw, author, timestamp_iso, metadata_raw = row
            try:
                payload = json.loads(content_raw) if isinstance(content_raw, str) else content_raw
                metadata = json.loads(metadata_raw) if isinstance(metadata_raw, str) else metadata_raw
                content = types.Content.model_validate(payload)
            except Exception:
                continue

            response.memories.append(
                MemoryEntry(
                    content=content,
                    id=str(memory_id),
                    author=author,
                    timestamp=timestamp_iso,
                    custom_metadata=metadata or {},
                )
            )
        return response
